### ISSUE TITLE
Insecure 302 redirection: HTTPS -> HTTP downgrading in OPDS links

### ISSUE THREAD

**Issue by johnbeard** [gbnewby/gutenbergsite#10]
Following links from the OPDS catalog results in a 302 redirect from an HTTPS to HTTP address:

Eg.
* https://www.gutenberg.org/ebooks/46.epub.noimages
 redirects to:
 * http://www.gutenberg.org/cache/epub/46/pg46.epub

This causes some clients to reject the redirection as insecure (which it is).

**Comment by eshellman** [comment]
a fix is in process

**Comment by eshellman** [comment]
This should be fixed - please reopen the issue if we've missed something
