### ISSUE TITLE
Missing link in /policy/permission.html

### ISSUE THREAD

**Issue by bottle2** [gbnewby/gutenbergsite#11]
Hey.

There's written "[...] clearly in the license included with each eBook, or read it here: License How-To" [here](https://github.com/gbnewby/gutenbergsite/blob/af507dd60fab718126a599e32fdd729c7086823c/site/policy/permission.md#commercial-use-of-project-gutenberg-trademark), but there's no link at all there.

**Comment by gbnewby** [comment]
Issue addressed.
