### ISSUE TITLE
Problems in some links

### ISSUE THREAD

**Issue by bottle2** [gbnewby/gutenbergsite#13]
Hey, I've noticed some things.

On [/policy/terms_of_use#audience](https://github.com/gbnewby/gutenbergsite/blob/af507dd60fab718126a599e32fdd729c7086823c/site/policy/terms_of_use.md#audience) the last link in the first bullet should be `[roboting guidelines](/policy/robot_access.html)` instead of `[roboting guidelines](/policy/robot_access.html")`. Later on in #opds-feed there's an improper space in `downloading our [catalog database] (/ebooks/offline_catalogs.html) and hosting` that should be removed. If you are pedantic on full stops, in the same page one could be added on the #trademark-license paragraph.

On [/policy/license](https://github.com/gbnewby/gutenbergsite/blob/master/site/policy/license.md) the first like should be `[/policy/permission.html](permission)` instead of `[/policy/permission.html](permissions)`.

On [/policy/permission#trademark-permission-to-trade-on-the-project-gutenberg-name](https://github.com/gbnewby/gutenbergsite/blob/af507dd60fab718126a599e32fdd729c7086823c/site/policy/permission.md#trademark-permission-to-trade-on-the-project-gutenberg-name) the link in `[...] trademark. The [/license](Small Print License) guides terms [...]` points nowhere.

On [/help/file_formats](https://github.com/gbnewby/gutenbergsite/blob/af507dd60fab718126a599e32fdd729c7086823c/site/help/file_formats.md) there is inconsistency when spacing links between `<` and `>`. I didn't saw use of angle brackets elsewhere, so maybe they could be removed entirely. Suppose you keep them and just correct spacing, you can replace `&lt;` and `&gt;` with literal angle brackets since Markdown automatically escape them. Also, some links are using `<a href="[...]">[...]</a>` instead of `[[...]]([...])`, but I guess that's no big deal.

Now, on dead links, there are many there. Suggestions follow:

- http://aspell.com/charsets/codepages.html => http://aspell.net/charsets/codepages.html
- https://aspell.com/charsets/iso8859.html => http://aspell.net/charsets/iso8859.html
- https://www.chiariglione.org/mpeg/ => https://mpeg.chiariglione.org/ or https://www.mpegstandards.org/
- https://www.iso.ch/ => https://www.iso.org/
- https://www.codamusic.com/ =>https://web.archive.org/web/20070225021311/https://www.codamusic.com/ (archive)
- https://www.gutenberg.net/music/music_helpex.html#what-software =>??? but should be in gutenberg.org domain
- https://www.mobipocket.com/ => https://web.archive.org/web/20130116044910/http://www.mobipocket.com/en/HomePage/default.asp?Language=EN

**Comment by gbnewby** [comment]
Thank you for these spectacularly useful fixes and suggestions. I believe all the fixes have now been applied. Let us know if we missed anything, or if you find further issues.

Thanks again, and best regards from Project Gutenberg.

**Comment by gbnewby** [comment]
Issues addressed.

**Comment by bottle2** [comment]
I have checked all pages I've pointed issues, but I'm afraid that the two links in [/help/file_formats#mpegmpg-format-for-moving-pictures](https://github.com/gbnewby/gutenbergsite/blob/1b313d95e88b0e46f86ddfe7b70afe3184ce6600/site/help/file_formats.md#mpegmpg-format-for-moving-pictures) still point to invalid pages. Apart from that, I'm glad the pages have been improved and thanks for keeping Gutenberg going!

**Comment by gbnewby** [comment]
Thanks! We missed those... now fixed. Very much appreciated!!
