### ISSUE TITLE
Running the project locally

### ISSUE THREAD

**Issue by tipsy** [gbnewby/gutenbergsite#18]
I tried to follow the instructions in the readme:

```
git clone https://github.com/gbnewby/gutenbergsite.git
cd gutenbergsite
bundle exec jekyll serve
```

And I got an error: `Could not locate Gemfile or .bundle/ directory`.

I think a `bundle install` step is missing, but it won't work without a Gemfile either way. Has the Gemfile not been checked in, or is there some way to specify to use the `Gemfile.old` which I saw was included?

**Comment by gbnewby** [comment]
It looks like we forgot to check in Gemfile. Gemfile.old is the same thing, though. We will check in a copy now, and then you can "bundle install" or "bundle update"

**Comment by gbnewby** [comment]
Thanks for reporting this issue!
