### ISSUE TITLE
Any help needed on the DB side?

### ISSUE THREAD

**Issue by lzambarda** [gbnewby/gutenbergsite#5]
Hello, I have stumbled in your project and I think I may be able to help with the "Search-related issues" issue written on http://dev.gutenberg.org/help/new_website.html
Are you currently looking to rework some of the backend as well?

**Comment by gbnewby** [comment]
Apologies for the long delay. We had other priorities, and are now looking at search.

We are seeking to implement Solr+Lucene. We are also interested in addressing some of the long-standing anomalies in the current search method, which basically uses PostgreSQL (our back-end database).

If these might be of interest, please get in touch ("contact information" at www.gutenberg.org). Thanks and best regards.
